# Generated by Django 3.2.19 on 2025-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0113_add_mostrar_callid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombrecalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='opcioncalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
