# Generated by Django 3.2.19 on 2025-08-20 08:55

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0113_add_mostrar_callid'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='auto_transcripcion',
            field=models.BooleanField(default=False, verbose_name='Habilitar transcripción'),
        ),
        migrations.AddField(
            model_name='queue',
            name='porcentaje_transcripcion',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='Porcentaje de transcripción',
            ),
        ),
    ]