# Generated by Django 3.2.19 on 2025-09-05 11:15

from django.db import migrations, models
from ominicontacto_app.models import MetadataBaseDatosContacto

def forwards_code(apps, schema_editor):
    Contacto = apps.get_model("ominicontacto_app", "Contacto")
    Contacto.objects_default.update(whatsapp=models.F("telefono"))
    BaseDatosContacto = apps.get_model("ominicontacto_app", "BaseDatosContacto")
    for bdc in BaseDatosContacto.objects.filter(campanas__whatsapp_habilitado=True).distinct("id"):
        metadata = MetadataBaseDatosContacto(bdc)
        metadata.columna_whatsapp = metadata.columnas_con_telefono[0]
        metadata.save()


def reverse_code(apps, schema_editor):
    BaseDatosContacto = apps.get_model("ominicontacto_app", "BaseDatosContacto")
    for bdc in BaseDatosContacto.objects.filter(campanas__whatsapp_habilitado=True).distinct("id"):
        metadata = MetadataBaseDatosContacto(bdc)
        metadata.columna_whatsapp = None
        metadata.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0114_auto_20250905_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(forwards_code, reverse_code),
    ]
