# Generated by Django 3.2.19 on 2025-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0114_auto_20250905_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
